### ISSUE TITLE
AttributeError - classifying step of rolling_s2_change_detection

### ISSUE THREAD

**Issue by ValentinLouis** [clcr/pyeo#45]
Error message:

tail COL_cartagena_S2_rolling_CD.e2668115 
/data/clcr/shared/miniconda3/envs/eoenv/lib/python3.6/site-packages/sklearn/base.py:311: UserWarning: Trying to unpickle estimator GridSearchCV from version 0.19.1 when using version 0.19.2. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
2019-03-28 17:24:07,878: INFO: Created classification image file: /data/clcr/shared/colombia/amazon/cartagena/output/categories/class_composite_T18NWF_20171230T152631_20180104T152629.tif
2019-03-28 17:24:07,878: WARNING: Model has no n_classes_ attribute (known issue with GridSearch)
Traceback (most recent call last):
  File "/data/clcr/vmhl1/pyeo/pyeo/apps/change_detection/rolling_composite_s2_change_detection.py", line 175, in <module>
    skip_existing=True, apply_mask=True)
  File "/data/clcr/vmhl1/pyeo/pyeo/core.py", line 1683, in classify_image
    prob_out_image = create_matching_dataset(image, prob_out_path, bands=model.n_classes_, datatype=gdal.GDT_Float32)
AttributeError: 'GridSearchCV' object has no attribute 'n_classes_'

Temporary fix:

prob_path in classify image function set to 'None'

**Comment by Thingus** [comment]
This one hasn't appeared since the refactoring, marking it closed.
