### ISSUE TITLE
create_masked_image() - shape mismatch

### ISSUE THREAD

**Issue by ValentinLouis** [clcr/pyeo#48]
2019-03-29 16:55:57,720: INFO: ****PROCESSING START****
Traceback (most recent call last):
  File "/home/ubuntu/pyeo/pyeo/tests/real_data_tests.py", line 433, in <module>
    masked_img_list = test_create_masked_image()
  File "/home/ubuntu/pyeo/pyeo/tests/real_data_tests.py", line 419, in test_create_masked_image
    masked_img = pyeo.create_masked_image(img, test_mask, test_out_path)
  File "/home/ubuntu/pyeo/pyeo/core.py", line 1659, in create_masked_image
    out_view[mask_view] = image_view
ValueError: shape mismatch: value array of shape (11023,10902) could not be broadcast to indexing result of shape (3675,3633,10902)

Process finished with exit code 1

**Comment by Thingus** [comment]
Issue hasn't reared it's head since, going to close this.
